GO
CREATE DATABASE DentaCare
GO
USE [DentaCare]
GO
/****** Object:  Table [dbo].[ACCOUNT] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACCOUNT](
	[accountID] [varchar](10) NOT NULL,
	[username] [varchar](40) NULL,
	[password] [varchar](250) NULL,
	[email] [varchar](30) NULL,
	[fullName] [nvarchar](50) NULL,
	[phone] [char](11) NULL,
	[address] [nvarchar](250) NULL,
	[dob] [date] NULL,
	[gender] [bit] NULL,
	[image] [varchar](200) NULL,
	[googleID] [varchar](100) NULL,
	[googleName] [varchar](100) NULL,
	[roleID] [int] NULL,
	[status] [int] NULL,
	[clinicID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[accountID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BOOKING] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BOOKING](
	[bookingID] [varchar](10) NOT NULL,
	[createDay] [date] NULL,
	[appointmentDay] [date] NULL,
	[status] [int] NULL,
	[price] [money] NULL,
	[deposit] [money] NULL,
	[serviceID] [int] NULL,
	[slotID] [int] NULL,
	[customerID] [varchar](10) NULL,
	[dentistID] [varchar](10) NULL,
	[clinicID] [int] NULL
PRIMARY KEY CLUSTERED 
(
	[bookingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CLINIC] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLINIC](
	[clinicID] [int] IDENTITY(1,1) NOT NULL,
	[clinicName] [varchar](50) NULL,
	[clinicAddress] [nvarchar](100) NULL,
	[city] [varchar](50) NULL,
	[hotline] [char](11) NULL,
PRIMARY KEY CLUSTERED 
(
	[clinicID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DAYOFFSCHEDULE] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DAYOFFSCHEDULE](
	[dayOffScheduleID] [int] IDENTITY(0,1) NOT NULL,
	[dayOff] [date] NULL,
	[description] [nvarchar](100) NULL,
	[clinicID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[dayOffScheduleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DENTISTSCHEDULE] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DENTISTSCHEDULE](
	[dentistScheduleID]  [int] IDENTITY(0,1) NOT NULL,
	[accountID] [varchar](10) NULL,
	[workingDate] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[dentistScheduleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FEEDBACK] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FEEDBACK](
	[feedbackID] [varchar](50) NOT NULL,
	[feedbackDay] [datetime] NULL,
	[feedbackContent] [nvarchar](max) NULL,
	[accountID] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[feedbackID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MAJOR] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MAJOR](
	[majorID] [varchar](3) NOT NULL,
	[majorName] [nvarchar](30) NULL,
	[majorDescription] [nvarchar](250) NULL,
PRIMARY KEY CLUSTERED 
(
	[majorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MAJORDETAIL] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MAJORDETAIL](
	[majorID] [varchar](3) NOT NULL,
	[accountID] [varchar](10) NOT NULL,
	[introduction] [nvarchar](500) NULL
PRIMARY KEY CLUSTERED 
(
	[majorID] ASC,
	[accountID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MEDIICALRECORDS] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MEDIICALRECORDS](
	[medicalRecordID] [varchar](10) NOT NULL,
	[results] [nvarchar](max) NULL,
	[reExanime] [date] NULL,
	[status] int NULL,
	[bookingID] [varchar](10) NULL
PRIMARY KEY CLUSTERED 
(
	[medicalRecordID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ROLE] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROLE](
	[roleID] [int] IDENTITY(0,1) NOT NULL,
	[roleName] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[roleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SERVICE] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SERVICE](
	[serviceID] [int] IDENTITY(0,1) NOT NULL,
	[serviceName] [nvarchar](50) NULL,
	[serviceType] [nvarchar](50) NULL,
	[description] [nvarchar](200) NULL,
	[price] [money] NULL,
	[status] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[serviceID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIMESLOT] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIMESLOT](
	[slotID] [int] IDENTITY(0,1) NOT NULL,
	[timePeriod] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[slotID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[PAYMENT] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAYMENT](
	[paymentID] [char](8) NOT NULL,
	[amount] [money] NULL,
	[orderInfo] [nvarchar](200) NULL,
	[responseCode] [int] NULL,
	[transactionNo] [char](8) NULL,
	[bankCode] [char](5) NULL,
	[paymentDay] [datetime] NULL,
	[bookingID] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[paymentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[INVOICE] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INVOICE](
	[invoiceID] [varchar](10) NOT NULL,
	[invoiceDay] [date] NULL,
	[invoiceStatus] [int] NULL,
	[bookingID] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[invoiceID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[SETTING] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SETTING](
	depositPercent int,
	limitBooking int
) 
GO

/* FOREIGN KEY roleID*/
ALTER TABLE [dbo].[ACCOUNT]  WITH CHECK ADD  CONSTRAINT [FK_roleID1] FOREIGN KEY([roleID])
REFERENCES [dbo].[ROLE] ([roleID])
GO
ALTER TABLE [dbo].[ACCOUNT] CHECK CONSTRAINT [FK_roleID1]
GO

/*FOREIGN KEY accountID*/
ALTER TABLE [dbo].[DENTISTSCHEDULE]  WITH CHECK ADD  CONSTRAINT [FK_accountID1] FOREIGN KEY([accountID])
REFERENCES [dbo].[ACCOUNT] ([accountID])
GO
ALTER TABLE [dbo].[DENTISTSCHEDULE] CHECK CONSTRAINT [FK_accountID1]
GO
ALTER TABLE [dbo].[MAJORDETAIL]  WITH CHECK ADD  CONSTRAINT [FK_accountID2] FOREIGN KEY([accountID])
REFERENCES [dbo].[ACCOUNT] ([accountID])
GO
ALTER TABLE [dbo].[MAJORDETAIL] CHECK CONSTRAINT [FK_accountID2]
GO
ALTER TABLE [dbo].[FEEDBACK]  WITH CHECK ADD  CONSTRAINT [FK_accountID3] FOREIGN KEY([accountID])
REFERENCES [dbo].[ACCOUNT] ([accountID])
GO
ALTER TABLE [dbo].[FEEDBACK] CHECK CONSTRAINT [FK_accountID3]
GO
ALTER TABLE [dbo].[BOOKING]  WITH CHECK ADD  CONSTRAINT [FK_accountID4] FOREIGN KEY([customerID])
REFERENCES [dbo].[ACCOUNT] ([accountID])
GO
ALTER TABLE [dbo].[BOOKING] CHECK CONSTRAINT [FK_accountID4]
GO
ALTER TABLE [dbo].[BOOKING]  WITH CHECK ADD  CONSTRAINT [FK_accountID5] FOREIGN KEY([dentistID])
REFERENCES [dbo].[ACCOUNT] ([accountID])
GO
ALTER TABLE [dbo].[BOOKING] CHECK CONSTRAINT [FK_accountID5]
GO

/*FOREIGN KEY clinicID*/
ALTER TABLE [dbo].[ACCOUNT]  WITH CHECK ADD  CONSTRAINT [FK_clinicID1] FOREIGN KEY([clinicID])
REFERENCES [dbo].[CLINIC] ([clinicID])
GO
ALTER TABLE [dbo].[ACCOUNT] CHECK CONSTRAINT [FK_clinicID1]
GO
ALTER TABLE [dbo].[DAYOFFSCHEDULE]  WITH CHECK ADD  CONSTRAINT [FK_clinicID2] FOREIGN KEY([clinicID])
REFERENCES [dbo].[CLINIC] ([clinicID])
GO
ALTER TABLE [dbo].[DAYOFFSCHEDULE] CHECK CONSTRAINT [FK_clinicID2]
GO
ALTER TABLE [dbo].[BOOKING]  WITH CHECK ADD  CONSTRAINT [FK_clinicID3] FOREIGN KEY([clinicID])
REFERENCES [dbo].[CLINIC] ([clinicID])
GO
ALTER TABLE [dbo].[BOOKING] CHECK CONSTRAINT [FK_clinicID3]
GO

/* FOREIGN KEY serviceID */
ALTER TABLE [dbo].[BOOKING]  WITH CHECK ADD  CONSTRAINT [FK_serviceID1] FOREIGN KEY([serviceID])
REFERENCES [dbo].[SERVICE] ([serviceID])
GO
ALTER TABLE [dbo].[BOOKING] CHECK CONSTRAINT [FK_serviceID1]
GO

/* FOREIGN KEY slotID */
ALTER TABLE [dbo].[BOOKING]  WITH CHECK ADD  CONSTRAINT [FK_slotID1] FOREIGN KEY([slotID])
REFERENCES [dbo].[TIMESLOT] ([slotID])
GO
ALTER TABLE [dbo].[BOOKING] CHECK CONSTRAINT [FK_slotID1]
GO

/* FOREIGN KEY majorID */
ALTER TABLE [dbo].[MAJORDETAIL]  WITH CHECK ADD  CONSTRAINT [FK_majorID1] FOREIGN KEY([majorID])
REFERENCES [dbo].[MAJOR] ([majorID])
GO
ALTER TABLE [dbo].[MAJORDETAIL] CHECK CONSTRAINT [FK_majorID1]
GO

/* FOREIGN KEY bookingID */
ALTER TABLE [dbo].[MEDIICALRECORDS]  WITH CHECK ADD  CONSTRAINT [FK_bookingID1] FOREIGN KEY([bookingID])
REFERENCES [dbo].[BOOKING] ([bookingID])
GO
ALTER TABLE [dbo].[MEDIICALRECORDS] CHECK CONSTRAINT [FK_bookingID1]
GO
ALTER TABLE [dbo].[PAYMENT]  WITH CHECK ADD  CONSTRAINT [FK_bookingID2] FOREIGN KEY([bookingID])
REFERENCES [dbo].[BOOKING] ([bookingID])
GO
ALTER TABLE [dbo].[PAYMENT] CHECK CONSTRAINT [FK_bookingID2]
GO
ALTER TABLE [dbo].[INVOICE]  WITH CHECK ADD  CONSTRAINT [FK_bookingID3] FOREIGN KEY([bookingID])
REFERENCES [dbo].[BOOKING] ([bookingID])
GO
ALTER TABLE [dbo].[INVOICE] CHECK CONSTRAINT [FK_bookingID3]
GO



INSERT INTO ROLE VALUES ('Customer'), ('Dentist'), ('Staff'), ('Clinic Owner')
insert into CLINIC values ('DentaCare1', 'clinicAddress1', 'city', '0123456789');
insert into CLINIC values ('DentaCare2', 'clinicAddress2', 'city', '0123456789');
insert into TIMESLOT values ('07:00 - 09:00'),('09:00 - 11:00'),('13:00 - 15:00'),('15:00 - 17:00');
INSERT INTO ACCOUNT VALUES('OWN2400001', 'hungAdmin', '993f2322f02ec3ce3d7849391b6f3668124130e83d32b96074bfa29c15d051b8', 'abc@gmail.com', null, null, null, null, null, null, null, null, 3, 0, null)